branches:
  except:
    - /travis/

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" cinst strawberryperl -y
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm --installdeps . -n
  - cpanm -n Moose Test::Output

build_script:
  - perl -e 1

test_script:
  - prove -lrv t/

skip_tags: true
